/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from './crisis-list.component.ngfactory';
import * as import6 from './hero-list.component.ngfactory';
import * as import7 from './app.component.ngfactory';
import * as import8 from '../../../src/app/crisis-list.component';
import * as import9 from '../../../src/app/hero-list.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵa_10:any;
  _UrlSerializer_11:import3.DefaultUrlSerializer;
  _RouterOutletMap_12:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_13:any;
  _LocationStrategy_14:any;
  _Location_15:import2.Location;
  _Compiler_16:import0.Compiler;
  _NgModuleFactoryLoader_17:import0.SystemJsNgModuleLoader;
  _ROUTES_18:any[];
  _Router_19:any;
  _RouterModule_20:import3.RouterModule;
  _AppModule_21:import1.AppModule;
  __LOCALE_ID_22:any;
  __NgLocalization_23:import2.NgLocaleLocalization;
  __APP_ID_24:any;
  __IterableDiffers_25:any;
  __KeyValueDiffers_26:any;
  __DomSanitizer_27:import4.ɵe;
  __Sanitizer_28:any;
  __HAMMER_GESTURE_CONFIG_29:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_30:any[];
  __EventManager_31:import4.EventManager;
  __ɵDomSharedStylesHost_32:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_33:import4.ɵDomRendererFactory2;
  __RendererFactory2_34:any;
  __ɵSharedStylesHost_35:any;
  __Testability_36:import0.Testability;
  __Meta_37:import4.Meta;
  __Title_38:import4.Title;
  __ActivatedRoute_39:any;
  __NoPreloading_40:import3.NoPreloading;
  __PreloadingStrategy_41:any;
  __RouterPreloader_42:import3.RouterPreloader;
  __PreloadAllModules_43:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_44:any;
  __APP_BOOTSTRAP_LISTENER_45:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import5.CrisisListComponentNgFactory,
      import6.HeroListComponentNgFactory,
      import7.AppComponentNgFactory
    ]
    ,[import7.AppComponentNgFactory]);
  }
  get _LOCALE_ID_22():any {
    if ((this.__LOCALE_ID_22 == null)) { (this.__LOCALE_ID_22 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_22;
  }
  get _NgLocalization_23():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_23 == null)) { (this.__NgLocalization_23 = new import2.NgLocaleLocalization(this._LOCALE_ID_22)); }
    return this.__NgLocalization_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == null)) { (this.__APP_ID_24 = import0.ɵg()); }
    return this.__APP_ID_24;
  }
  get _IterableDiffers_25():any {
    if ((this.__IterableDiffers_25 == null)) { (this.__IterableDiffers_25 = import0.ɵl()); }
    return this.__IterableDiffers_25;
  }
  get _KeyValueDiffers_26():any {
    if ((this.__KeyValueDiffers_26 == null)) { (this.__KeyValueDiffers_26 = import0.ɵm()); }
    return this.__KeyValueDiffers_26;
  }
  get _DomSanitizer_27():import4.ɵe {
    if ((this.__DomSanitizer_27 == null)) { (this.__DomSanitizer_27 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == null)) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _HAMMER_GESTURE_CONFIG_29():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_29 == null)) { (this.__HAMMER_GESTURE_CONFIG_29 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_29;
  }
  get _EVENT_MANAGER_PLUGINS_30():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_30 == null)) { (this.__EVENT_MANAGER_PLUGINS_30 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_29)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_30;
  }
  get _EventManager_31():import4.EventManager {
    if ((this.__EventManager_31 == null)) { (this.__EventManager_31 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_30,this.parent.get(import0.NgZone))); }
    return this.__EventManager_31;
  }
  get _ɵDomSharedStylesHost_32():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_32 == null)) { (this.__ɵDomSharedStylesHost_32 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_32;
  }
  get _ɵDomRendererFactory2_33():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_33 == null)) { (this.__ɵDomRendererFactory2_33 = new import4.ɵDomRendererFactory2(this._EventManager_31,this._ɵDomSharedStylesHost_32)); }
    return this.__ɵDomRendererFactory2_33;
  }
  get _RendererFactory2_34():any {
    if ((this.__RendererFactory2_34 == null)) { (this.__RendererFactory2_34 = this._ɵDomRendererFactory2_33); }
    return this.__RendererFactory2_34;
  }
  get _ɵSharedStylesHost_35():any {
    if ((this.__ɵSharedStylesHost_35 == null)) { (this.__ɵSharedStylesHost_35 = this._ɵDomSharedStylesHost_32); }
    return this.__ɵSharedStylesHost_35;
  }
  get _Testability_36():import0.Testability {
    if ((this.__Testability_36 == null)) { (this.__Testability_36 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_36;
  }
  get _Meta_37():import4.Meta {
    if ((this.__Meta_37 == null)) { (this.__Meta_37 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_37;
  }
  get _Title_38():import4.Title {
    if ((this.__Title_38 == null)) { (this.__Title_38 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_38;
  }
  get _ActivatedRoute_39():any {
    if ((this.__ActivatedRoute_39 == null)) { (this.__ActivatedRoute_39 = import3.ɵf(this._Router_19)); }
    return this.__ActivatedRoute_39;
  }
  get _NoPreloading_40():import3.NoPreloading {
    if ((this.__NoPreloading_40 == null)) { (this.__NoPreloading_40 = new import3.NoPreloading()); }
    return this.__NoPreloading_40;
  }
  get _PreloadingStrategy_41():any {
    if ((this.__PreloadingStrategy_41 == null)) { (this.__PreloadingStrategy_41 = this._NoPreloading_40); }
    return this.__PreloadingStrategy_41;
  }
  get _RouterPreloader_42():import3.RouterPreloader {
    if ((this.__RouterPreloader_42 == null)) { (this.__RouterPreloader_42 = new import3.RouterPreloader(this._Router_19,this._NgModuleFactoryLoader_17,this._Compiler_16,this,this._PreloadingStrategy_41)); }
    return this.__RouterPreloader_42;
  }
  get _PreloadAllModules_43():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_43 == null)) { (this.__PreloadAllModules_43 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_43;
  }
  get _ROUTER_INITIALIZER_44():any {
    if ((this.__ROUTER_INITIALIZER_44 == null)) { (this.__ROUTER_INITIALIZER_44 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_44;
  }
  get _APP_BOOTSTRAP_LISTENER_45():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_45 == null)) { (this.__APP_BOOTSTRAP_LISTENER_45 = [this._ROUTER_INITIALIZER_44]); }
    return this.__APP_BOOTSTRAP_LISTENER_45;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵa_10 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_11 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_12 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_13 = {};
    this._LocationStrategy_14 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_13);
    this._Location_15 = new import2.Location(this._LocationStrategy_14);
    this._Compiler_16 = new import0.Compiler();
    this._NgModuleFactoryLoader_17 = new import0.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_18 = [[
        {
          path: 'crisis-center',
          component: import8.CrisisListComponent
        }
        ,
        {
          path: 'heroes',
          component: import9.HeroListComponent
        }
        ,
        {
          path: '',
          redirectTo: '/heroes',
          pathMatch: 'full'
        }

      ]
    ];
    this._Router_19 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_11,this._RouterOutletMap_12,this._Location_15,this,this._NgModuleFactoryLoader_17,this._Compiler_16,this._ROUTES_18,this._ROUTER_CONFIGURATION_13,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_20 = new import3.RouterModule(this._ɵa_10,this._Router_19);
    this._AppModule_21 = new import1.AppModule();
    return this._AppModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import3.ɵa)) { return this._ɵa_10; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_11; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_12; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_13; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_14; }
    if ((token === import2.Location)) { return this._Location_15; }
    if ((token === import0.Compiler)) { return this._Compiler_16; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_17; }
    if ((token === import3.ROUTES)) { return this._ROUTES_18; }
    if ((token === import3.Router)) { return this._Router_19; }
    if ((token === import3.RouterModule)) { return this._RouterModule_20; }
    if ((token === import1.AppModule)) { return this._AppModule_21; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_22; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_23; }
    if ((token === import0.APP_ID)) { return this._APP_ID_24; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_25; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_26; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_29; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_30; }
    if ((token === import4.EventManager)) { return this._EventManager_31; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_32; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_33; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_34; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_35; }
    if ((token === import0.Testability)) { return this._Testability_36; }
    if ((token === import4.Meta)) { return this._Meta_37; }
    if ((token === import4.Title)) { return this._Title_38; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_39; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_40; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_41; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_42; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_43; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_44; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_45; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_32 && this._ɵDomSharedStylesHost_32.ngOnDestroy());
    (this.__RouterPreloader_42 && this._RouterPreloader_42.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
