/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/crisis-list.component';
const styles_CrisisListComponent:any[] = ([] as any[]);
export const RenderType_CrisisListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CrisisListComponent,
  data: {}
}
);
export function View_CrisisListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['CRISIS CENTER'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Get your crisis here']))
  ]
  ,(null as any),(null as any));
}
function View_CrisisListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_CrisisListComponent_0,RenderType_CrisisListComponent)),
    import0.ɵdid(24576,(null as any),0,import1.CrisisListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CrisisListComponentNgFactory:import0.ComponentFactory<import1.CrisisListComponent> = import0.ɵccf('ng-component',import1.CrisisListComponent,View_CrisisListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9jcmlzaXMtbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYWFnL0FwcGxpY2F0aW9ucy93b3Jrc3BhY2UvcXVpY2tzdGFydC9zcmMvYXBwL2NyaXNpcy1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9jcmlzaXMtbGlzdC5jb21wb25lbnQudHMuQ3Jpc2lzTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYWFnL0FwcGxpY2F0aW9ucy93b3Jrc3BhY2UvcXVpY2tzdGFydC9zcmMvYXBwL2NyaXNpcy1saXN0LmNvbXBvbmVudC50cy5DcmlzaXNMaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGgyPkNSSVNJUyBDRU5URVI8L2gyPlxuICAgIDxwPkdldCB5b3VyIGNyaXNpcyBoZXJlPC9wPiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSTtJQUFrQjtJQUN0QjtJQUFHOzs7Ozs7SUNGUDtnQkFBQTs7OzsifQ==
