/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/hero-list.component';
const styles_HeroListComponent:any[] = ([] as any[]);
export const RenderType_HeroListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HeroListComponent,
  data: {}
}
);
export function View_HeroListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['HEROES'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Get your heroes here'])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_HeroListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HeroListComponent_0,RenderType_HeroListComponent)),
    import0.ɵdid(24576,(null as any),0,import1.HeroListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HeroListComponentNgFactory:import0.ComponentFactory<import1.HeroListComponent> = import0.ɵccf('ng-component',import1.HeroListComponent,View_HeroListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9oZXJvLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9oZXJvLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYWFnL0FwcGxpY2F0aW9ucy93b3Jrc3BhY2UvcXVpY2tzdGFydC9zcmMvYXBwL2hlcm8tbGlzdC5jb21wb25lbnQudHMuSGVyb0xpc3RDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FhZy9BcHBsaWNhdGlvbnMvd29ya3NwYWNlL3F1aWNrc3RhcnQvc3JjL2FwcC9oZXJvLWxpc3QuY29tcG9uZW50LnRzLkhlcm9MaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGgyPkhFUk9FUzwvaDI+XG4gICAgPHA+R2V0IHlvdXIgaGVyb2VzIGhlcmU8L3A+XG4gICIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSTtJQUFXO0lBQ2Y7SUFBRztJQUF3Qjs7Ozs7O0lDRi9CO2dCQUFBOzs7OyJ9
